name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: get dependencies
        run: yarn

      - name: build
        run: yarn build

      - name: show changes
        run: git status

      - name: semver
        id: semver
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          init-version: 1.0.0

      - name: commit and push change
        if: ${{ steps.semver.outputs.released == 'true' }}
        env:
          VERSION: ${{ steps.semver.outputs.version }}
        run: |
          git add dist
          git diff-index --quiet HEAD || git commit -m "Release ${VERSION}"
          git push

      - name: update tag
        if: ${{ steps.semver.outputs.released == 'true' }}
        env:
          TAG: ${{ steps.semver.outputs.tag-prefix }}${{ steps.semver.outputs.version-major }}
        run: |
          git tag -f ${TAG}
          git push origin ${TAG} --force
